version: '3'
services:
  db:
    image: mdillon/postgis:11
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FoodtruckerTest
    ports:
    - 127.0.0.1:15432:5432