version: "3"
services:
  app:
    image: docker.miroslawgalczynski.com/foodtrucker
    restart: always
    ports:
      - 127.0.0.1:$PORT:80
    networks:
      - internal
      - public

  db:
    image: mdillon/postgis:11
    restart: always
    volumes:
      - /var/foodtrucker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Foodtrucker
      POSTGRES_DB: Foodtrucker
      POSTGRES_USER: Foodtrucker
    networks:
      - internal

networks:
  internal:
    internal: true
  public:
    internal: false
