version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
    - ./db:/var/lib/postgresql/data
    environment:
    - ACCEPT_EULA=y
    - SA_PASSWORD=yourStrong(!)Password
    ports:
    - 127.0.0.1:1433:1433